steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'kabumterimon',
  '--runtime=nodejs10',
  '--trigger-http',
  '--entry-point=process',
  '--project=kabumterimon',
  '--timeout=300']
  dir: kabumterimon/backend