steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'kabumterimon',
  '--runtime=nodejs10',
  '--trigger-http',
  '--entry-point=process',
  '--project=kabumterimon',
  "--set-env-vars=\
  GCLOUD_CLOUDRUN_ENDPOINT=$_GCLOUD_CLOUDRUN_ENDPOINT,\
  GCLOUD_TOPIC=$_GCLOUD_TOPIC",
  '--timeout=300']